# Some notes:
# "build: ." will build the dockerfile in the same folder of this file
# When mem_limit == memswap_limit swap is disabled for the container.
# Cpuset is the list of cpu cores that the container can use.

services:
  node1:
    build: .
    ports:
      - "1881:1883"
    volumes:
      - "./configs/mqtt-fed1.toml:/mqtt-fed.toml"
    cpuset: "0"
    mem_limit: 1g
    memswap_limit: 1g

  node2:
    build: .
    ports:
      - "1882:1883"
    volumes:
      - "./configs/mqtt-fed2.toml:/mqtt-fed.toml"
    cpuset: "1"
    mem_limit: 1g
    memswap_limit: 1g

  node3:
    build: .
    ports:
      - "1883:1883"
    volumes:
      - "./configs/mqtt-fed3.toml:/mqtt-fed.toml"
    cpuset: "2"
    mem_limit: 1g
    memswap_limit: 1g

  node4:
    build: .
    ports:
      - "1884:1883"
    volumes:
      - "./configs/mqtt-fed4.toml:/mqtt-fed.toml"
    cpuset: "3"
    mem_limit: 1g
    memswap_limit: 1g

  node5:
    build: .
    ports:
      - "1885:1883"
    volumes:
      - "./configs/mqtt-fed5.toml:/mqtt-fed.toml"
    cpuset: "4"
    mem_limit: 1g
    memswap_limit: 1g
